//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Du_Lich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDATTOUR
    {
        public int SoHD { get; set; }
        public Nullable<int> MaHK { get; set; }
        public string MaTour { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public double PTGiam { get; set; }
        public string TenTV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual HANHKHACH HANHKHACH { get; set; }
        public virtual TOUR TOUR { get; set; }
        public virtual DONDATTOUR DONDATTOUR { get; set; }
    }
}
