//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Du_Lich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATTOUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONDATTOUR()
        {
            this.CTDATTOURs = new HashSet<CTDATTOUR>();
        }
    
        public int SoHD { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string HoTenKH { get; set; }
        public string SDT_KH { get; set; }
        public string EmailKH { get; set; }
        public string DiaChiKH { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<bool> HTThanhToan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> PTThanhToan { get; set; }
        public string MaTour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATTOUR> CTDATTOURs { get; set; }
        public virtual TOUR TOUR { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
