//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Du_Lich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHSAN
    {
        public string MaKS { get; set; }
        public string TenKS { get; set; }
        public decimal GiaKS { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaLKS { get; set; }
    
        public virtual LOAIK LOAIK { get; set; }
    }
}
