//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Du_Lich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTRINH
    {
        public int SoTT { get; set; }
        public string MaTour { get; set; }
        public int MaDD { get; set; }
        public Nullable<System.DateTime> ThoiGianDi { get; set; }
        public string MoTa { get; set; }
        public string TenLichTrinh { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
