//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Du_Lich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.CTDATTOURs = new HashSet<CTDATTOUR>();
            this.DONDATTOURs = new HashSet<DONDATTOUR>();
            this.LICHTRINHs = new HashSet<LICHTRINH>();
        }
    
        public string MaTour { get; set; }
        public string TenTour { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }
        public string MoTa { get; set; }
        public int SoLuongConLai { get; set; }
        public Nullable<System.DateTime> NgayDiTour { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> MaDDi { get; set; }
        public Nullable<int> MaDDen { get; set; }
        public Nullable<int> MaLoaiTour { get; set; }
        public Nullable<int> MaPT { get; set; }
        public Nullable<int> MaLKS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATTOUR> CTDATTOURs { get; set; }
        public virtual DIEMDEN DIEMDEN { get; set; }
        public virtual DIEMDI DIEMDI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATTOUR> DONDATTOURs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTRINH> LICHTRINHs { get; set; }
        public virtual LOAIK LOAIK { get; set; }
        public virtual LOAITOUR LOAITOUR { get; set; }
        public virtual PHUONGTIEN PHUONGTIEN { get; set; }
    }
}
