//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Du_Lich.Models
{
    using MVC_Du_Lich.Design_Pattern.Creational_Pattern.Builder;
    using MVC_Du_Lich.Design_Pattern.Creational_Pattern.Prototype;
    using System;
    using System.Collections.Generic;

    public partial class TOUR : Prototype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.CTDATTOURs = new HashSet<CTDATTOUR>();
            this.DONDATTOURs = new HashSet<DONDATTOUR>();
            this.LICHTRINHs = new HashSet<LICHTRINH>();
        }

        public TOUR(string maTour, string tenTour, decimal gia, int soLuong, string hinh1, string hinh2, string hinh3,
            string hinh4, string moTa, int slconlai, DateTime ngayDiTour, DateTime ngayKetThuc, int maDDi, int maDDen,
            int maLoaiTour, int maPT, int maLKS)
        {
            this.MaTour = maTour;
            this.TenTour = tenTour;
            this.Gia = gia;
            this.SoLuong = soLuong;
            this.Hinh1 = hinh1;
            this.Hinh2 = hinh2;
            this.Hinh3 = hinh3;
            this.Hinh4 = hinh4;
            this.MoTa = moTa;
            this.SoLuongConLai = slconlai;
            this.NgayDiTour = ngayDiTour;
            this.NgayKetThuc = ngayKetThuc;
            this.MaDDi = maDDi;
            this.MaDDen = maDDen;
            this.MaLoaiTour = maLoaiTour;
            this.MaPT = maPT;
            this.MaLKS = maLKS;
        }

        public string MaTour { get; set; }
        public string TenTour { get; set; }
        public decimal Gia { get; set; }
        public int SoLuong { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }
        public string MoTa { get; set; }
        public int SoLuongConLai { get; set; }
        public System.DateTime NgayDiTour { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public int MaDDi { get; set; }
        public int MaDDen { get; set; }
        public int MaLoaiTour { get; set; }
        public int MaPT { get; set; }
        public int MaLKS { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATTOUR> CTDATTOURs { get; set; }
        public virtual DIEMDEN DIEMDEN { get; set; }
        public virtual DIEMDI DIEMDI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATTOUR> DONDATTOURs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTRINH> LICHTRINHs { get; set; }
        public virtual LOAIK LOAIK { get; set; }
        public virtual LOAITOUR LOAITOUR { get; set; }
        public virtual PHUONGTIEN PHUONGTIEN { get; set; }

        public override Prototype Clone(TOUR origintour, string maTour)
        {
            var tour = new TOUR
            {
                MaTour = maTour,
                TenTour = origintour.TenTour,
                Gia = origintour.Gia,
                SoLuong = origintour.SoLuong,
                Hinh1 = origintour.Hinh1,
                Hinh2 = origintour.Hinh2,
                Hinh3 = origintour.Hinh3,
                Hinh4 = origintour.Hinh4,
                MoTa = origintour.MoTa,
                SoLuongConLai = origintour.SoLuongConLai,
                NgayDiTour = origintour.NgayDiTour,
                NgayKetThuc = origintour.NgayKetThuc,
                MaDDi = origintour.MaDDi,
                MaDDen = origintour.MaDDen,
                MaLoaiTour = origintour.MaLoaiTour,
                MaPT = origintour.MaPT,
                MaLKS = origintour.MaLKS,
            };
            return (TOUR)tour;
        }
    }
}
